name: Build and Deploy

on: 
  push:
    branches: [develop2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: PRODU
    env:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      #AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_ENVIRONMENT: PROD

    steps:
     - uses: actions/checkout@v2
     - name: Build & Zip
       run: |
         pwd 
         ls -a 
         zip -r index.zip .
         ls -a
         echo "S3_BUCKET: ${{ env.S3_BUCKET }}"
         echo "AWS ROLE: ${{ env.AWS_ROLE_TO_ASSUME }}"
         echo "Hola soy iu"

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with: 
         #role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
         aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}
         #role-duration-seconds: 2400
         aws-region: us-east-1
         role-skip-session-tagging: true

     - name: Push to S3 Bucket
       run: | 
         aws s3 cp index.zip s3://${{ env.S3_BUCKET }}       

     - name: Copy file from repoGitHUb
       run: |
          pwd 
          mkdir copyt
          cd copyt
          ls -a
          git init 
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/Isusquiza/terrena.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull 
          ls -a 
          aws s3 cp ./ s3://${{ env.S3_BUCKET }} 
          #git add -A
          #git commit -m "Random File"
          #git push   




        
    


  


